// Flutter imports:
import 'package:flutter/material.dart';

class YellowColorScheme extends ColorScheme {
  YellowColorScheme({
    required super.brightness,
    required super.primary,
    required super.onPrimary,
    Color? super.primaryContainer,
    Color? super.onPrimaryContainer,
    Color? super.primaryFixed,
    Color? super.primaryFixedDim,
    Color? super.onPrimaryFixed,
    Color? super.onPrimaryFixedVariant,
    required super.secondary,
    required super.onSecondary,
    Color? super.secondaryContainer,
    Color? super.onSecondaryContainer,
    Color? super.secondaryFixed,
    Color? super.secondaryFixedDim,
    Color? super.onSecondaryFixed,
    Color? super.onSecondaryFixedVariant,
    Color? super.tertiary,
    Color? super.onTertiary,
    Color? super.tertiaryContainer,
    Color? super.onTertiaryContainer,
    Color? super.tertiaryFixed,
    Color? super.tertiaryFixedDim,
    Color? super.onTertiaryFixed,
    Color? super.onTertiaryFixedVariant,
    required super.error,
    required super.onError,
    Color? super.errorContainer,
    Color? super.onErrorContainer,
    required super.surface,
    required super.onSurface,
    Color? super.surfaceDim,
    Color? super.surfaceBright,
    Color? super.surfaceContainerLowest,
    Color? super.surfaceContainerLow,
    Color? super.surfaceContainer,
    Color? super.surfaceContainerHigh,
    Color? super.surfaceContainerHighest,
    Color? super.onSurfaceVariant,
    Color? super.outline,
    Color? super.outlineVariant,
    Color? super.shadow,
    Color? super.scrim,
    Color? super.inverseSurface,
    Color? super.onInverseSurface,
    Color? super.inversePrimary,
    Color? super.surfaceTint,
  });
}
