// Windows Virtual-Key codes based on Microsoft documentation:
// https://learn.microsoft.com/windows/win32/inputdev/virtual-key-codes
//
// Note: VK_F13 (0x7C) - VK_F24 (0x87) are intentionally excluded because this
// project reserves those keycodes for macros (see `MonitorKeycodes`).

enum VirtualKeyCode {
  lButton(0x01, 'VK_LBUTTON'),
  rButton(0x02, 'VK_RBUTTON'),
  cancel(0x03, 'VK_CANCEL'),
  mButton(0x04, 'VK_MBUTTON'),
  xButton1(0x05, 'VK_XBUTTON1'),
  xButton2(0x06, 'VK_XBUTTON2'),

  backspace(0x08, 'VK_BACK'),
  tab(0x09, 'VK_TAB'),

  clear(0x0C, 'VK_CLEAR'),
  enter(0x0D, 'VK_RETURN'),

  shift(0x10, 'VK_SHIFT'),
  control(0x11, 'VK_CONTROL'),
  alt(0x12, 'VK_MENU'),
  pause(0x13, 'VK_PAUSE'),
  capsLock(0x14, 'VK_CAPITAL'),

  kana(0x15, 'VK_KANA'),
  hangul(0x15, 'VK_HANGUL'),
  imeOn(0x16, 'VK_IME_ON'),
  junja(0x17, 'VK_JUNJA'),
  finalMode(0x18, 'VK_FINAL'),
  hanja(0x19, 'VK_HANJA'),
  kanji(0x19, 'VK_KANJI'),
  imeOff(0x1A, 'VK_IME_OFF'),

  escape(0x1B, 'VK_ESCAPE'),
  convert(0x1C, 'VK_CONVERT'),
  nonConvert(0x1D, 'VK_NONCONVERT'),
  accept(0x1E, 'VK_ACCEPT'),
  modeChange(0x1F, 'VK_MODECHANGE'),

  space(0x20, 'VK_SPACE'),
  pageUp(0x21, 'VK_PRIOR'),
  pageDown(0x22, 'VK_NEXT'),
  end(0x23, 'VK_END'),
  home(0x24, 'VK_HOME'),
  left(0x25, 'VK_LEFT'),
  up(0x26, 'VK_UP'),
  right(0x27, 'VK_RIGHT'),
  down(0x28, 'VK_DOWN'),
  select(0x29, 'VK_SELECT'),
  print(0x2A, 'VK_PRINT'),
  execute(0x2B, 'VK_EXECUTE'),
  printScreen(0x2C, 'VK_SNAPSHOT'),
  insert(0x2D, 'VK_INSERT'),
  delete(0x2E, 'VK_DELETE'),
  help(0x2F, 'VK_HELP'),

  digit0(0x30, '0'),
  digit1(0x31, '1'),
  digit2(0x32, '2'),
  digit3(0x33, '3'),
  digit4(0x34, '4'),
  digit5(0x35, '5'),
  digit6(0x36, '6'),
  digit7(0x37, '7'),
  digit8(0x38, '8'),
  digit9(0x39, '9'),

  keyA(0x41, 'A'),
  keyB(0x42, 'B'),
  keyC(0x43, 'C'),
  keyD(0x44, 'D'),
  keyE(0x45, 'E'),
  keyF(0x46, 'F'),
  keyG(0x47, 'G'),
  keyH(0x48, 'H'),
  keyI(0x49, 'I'),
  keyJ(0x4A, 'J'),
  keyK(0x4B, 'K'),
  keyL(0x4C, 'L'),
  keyM(0x4D, 'M'),
  keyN(0x4E, 'N'),
  keyO(0x4F, 'O'),
  keyP(0x50, 'P'),
  keyQ(0x51, 'Q'),
  keyR(0x52, 'R'),
  keyS(0x53, 'S'),
  keyT(0x54, 'T'),
  keyU(0x55, 'U'),
  keyV(0x56, 'V'),
  keyW(0x57, 'W'),
  keyX(0x58, 'X'),
  keyY(0x59, 'Y'),
  keyZ(0x5A, 'Z'),

  leftWindows(0x5B, 'VK_LWIN'),
  rightWindows(0x5C, 'VK_RWIN'),
  apps(0x5D, 'VK_APPS'),
  sleep(0x5F, 'VK_SLEEP'),

  numpad0(0x60, 'VK_NUMPAD0'),
  numpad1(0x61, 'VK_NUMPAD1'),
  numpad2(0x62, 'VK_NUMPAD2'),
  numpad3(0x63, 'VK_NUMPAD3'),
  numpad4(0x64, 'VK_NUMPAD4'),
  numpad5(0x65, 'VK_NUMPAD5'),
  numpad6(0x66, 'VK_NUMPAD6'),
  numpad7(0x67, 'VK_NUMPAD7'),
  numpad8(0x68, 'VK_NUMPAD8'),
  numpad9(0x69, 'VK_NUMPAD9'),
  multiply(0x6A, 'VK_MULTIPLY'),
  add(0x6B, 'VK_ADD'),
  separator(0x6C, 'VK_SEPARATOR'),
  subtract(0x6D, 'VK_SUBTRACT'),
  decimal(0x6E, 'VK_DECIMAL'),
  divide(0x6F, 'VK_DIVIDE'),

  f1(0x70, 'VK_F1'),
  f2(0x71, 'VK_F2'),
  f3(0x72, 'VK_F3'),
  f4(0x73, 'VK_F4'),
  f5(0x74, 'VK_F5'),
  f6(0x75, 'VK_F6'),
  f7(0x76, 'VK_F7'),
  f8(0x77, 'VK_F8'),
  f9(0x78, 'VK_F9'),
  f10(0x79, 'VK_F10'),
  f11(0x7A, 'VK_F11'),
  f12(0x7B, 'VK_F12'),

  numLock(0x90, 'VK_NUMLOCK'),
  scrollLock(0x91, 'VK_SCROLL'),

  leftShift(0xA0, 'VK_LSHIFT'),
  rightShift(0xA1, 'VK_RSHIFT'),
  leftControl(0xA2, 'VK_LCONTROL'),
  rightControl(0xA3, 'VK_RCONTROL'),
  leftAlt(0xA4, 'VK_LMENU'),
  rightAlt(0xA5, 'VK_RMENU'),

  browserBack(0xA6, 'VK_BROWSER_BACK'),
  browserForward(0xA7, 'VK_BROWSER_FORWARD'),
  browserRefresh(0xA8, 'VK_BROWSER_REFRESH'),
  browserStop(0xA9, 'VK_BROWSER_STOP'),
  browserSearch(0xAA, 'VK_BROWSER_SEARCH'),
  browserFavorites(0xAB, 'VK_BROWSER_FAVORITES'),
  browserHome(0xAC, 'VK_BROWSER_HOME'),

  volumeMute(0xAD, 'VK_VOLUME_MUTE'),
  volumeDown(0xAE, 'VK_VOLUME_DOWN'),
  volumeUp(0xAF, 'VK_VOLUME_UP'),
  mediaNextTrack(0xB0, 'VK_MEDIA_NEXT_TRACK'),
  mediaPrevTrack(0xB1, 'VK_MEDIA_PREV_TRACK'),
  mediaStop(0xB2, 'VK_MEDIA_STOP'),
  mediaPlayPause(0xB3, 'VK_MEDIA_PLAY_PAUSE'),
  launchMail(0xB4, 'VK_LAUNCH_MAIL'),
  launchMediaSelect(0xB5, 'VK_LAUNCH_MEDIA_SELECT'),
  launchApp1(0xB6, 'VK_LAUNCH_APP1'),
  launchApp2(0xB7, 'VK_LAUNCH_APP2'),

  oem1(0xBA, 'VK_OEM_1'),
  oemPlus(0xBB, 'VK_OEM_PLUS'),
  oemComma(0xBC, 'VK_OEM_COMMA'),
  oemMinus(0xBD, 'VK_OEM_MINUS'),
  oemPeriod(0xBE, 'VK_OEM_PERIOD'),
  oem2(0xBF, 'VK_OEM_2'),
  oem3(0xC0, 'VK_OEM_3'),

  gamepadA(0xC3, 'VK_GAMEPAD_A'),
  gamepadB(0xC4, 'VK_GAMEPAD_B'),
  gamepadX(0xC5, 'VK_GAMEPAD_X'),
  gamepadY(0xC6, 'VK_GAMEPAD_Y'),
  gamepadRightShoulder(0xC7, 'VK_GAMEPAD_RIGHT_SHOULDER'),
  gamepadLeftShoulder(0xC8, 'VK_GAMEPAD_LEFT_SHOULDER'),
  gamepadLeftTrigger(0xC9, 'VK_GAMEPAD_LEFT_TRIGGER'),
  gamepadRightTrigger(0xCA, 'VK_GAMEPAD_RIGHT_TRIGGER'),
  gamepadDpadUp(0xCB, 'VK_GAMEPAD_DPAD_UP'),
  gamepadDpadDown(0xCC, 'VK_GAMEPAD_DPAD_DOWN'),
  gamepadDpadLeft(0xCD, 'VK_GAMEPAD_DPAD_LEFT'),
  gamepadDpadRight(0xCE, 'VK_GAMEPAD_DPAD_RIGHT'),
  gamepadMenu(0xCF, 'VK_GAMEPAD_MENU'),
  gamepadView(0xD0, 'VK_GAMEPAD_VIEW'),
  gamepadLeftThumbstickButton(0xD1, 'VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON'),
  gamepadRightThumbstickButton(0xD2, 'VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON'),
  gamepadLeftThumbstickUp(0xD3, 'VK_GAMEPAD_LEFT_THUMBSTICK_UP'),
  gamepadLeftThumbstickDown(0xD4, 'VK_GAMEPAD_LEFT_THUMBSTICK_DOWN'),
  gamepadLeftThumbstickRight(0xD5, 'VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT'),
  gamepadLeftThumbstickLeft(0xD6, 'VK_GAMEPAD_LEFT_THUMBSTICK_LEFT'),
  gamepadRightThumbstickUp(0xD7, 'VK_GAMEPAD_RIGHT_THUMBSTICK_UP'),
  gamepadRightThumbstickDown(0xD8, 'VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN'),
  gamepadRightThumbstickRight(0xD9, 'VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT'),
  gamepadRightThumbstickLeft(0xDA, 'VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT'),

  oem4(0xDB, 'VK_OEM_4'),
  oem5(0xDC, 'VK_OEM_5'),
  oem6(0xDD, 'VK_OEM_6'),
  oem7(0xDE, 'VK_OEM_7'),
  oem8(0xDF, 'VK_OEM_8'),
  oem102(0xE2, 'VK_OEM_102'),

  processKey(0xE5, 'VK_PROCESSKEY'),
  packet(0xE7, 'VK_PACKET'),

  attn(0xF6, 'VK_ATTN'),
  crSel(0xF7, 'VK_CRSEL'),
  exSel(0xF8, 'VK_EXSEL'),
  eraseEof(0xF9, 'VK_EREOF'),
  play(0xFA, 'VK_PLAY'),
  zoom(0xFB, 'VK_ZOOM'),
  pa1(0xFD, 'VK_PA1'),
  oemClear(0xFE, 'VK_OEM_CLEAR');

  final int vkCode;
  final String label;

  const VirtualKeyCode(this.vkCode, this.label);

  static VirtualKeyCode? tryFromVkCode(int vkCode) {
    for (final value in VirtualKeyCode.values) {
      if (value.vkCode == vkCode) return value;
    }
    return null;
  }
}
