// Windows Virtual-Key codes based on Microsoft documentation:
// https://learn.microsoft.com/windows/win32/inputdev/virtual-key-codes
//
// Note: F13 (0x7C) - F24 (0x87) are intentionally excluded because this
// project reserves those keycodes for macros (see `MonitorKeycodes`).

enum VirtualKeyCode {
  lButton(0x01, 'LBUTTON'),
  rButton(0x02, 'RBUTTON'),
  cancel(0x03, 'CANCEL'),
  mButton(0x04, 'MBUTTON'),
  xButton1(0x05, 'XBUTTON1'),
  xButton2(0x06, 'XBUTTON2'),

  backspace(0x08, 'BACK'),
  tab(0x09, 'TAB'),

  clear(0x0C, 'CLEAR'),
  enter(0x0D, 'RETURN'),

  shift(0x10, 'SHIFT'),
  control(0x11, 'CONTROL'),
  alt(0x12, 'MENU'),
  pause(0x13, 'PAUSE'),
  capsLock(0x14, 'CAPITAL'),

  kana(0x15, 'KANA'),
  hangul(0x15, 'HANGUL'),
  imeOn(0x16, 'IME_ON'),
  junja(0x17, 'JUNJA'),
  finalMode(0x18, 'FINAL'),
  hanja(0x19, 'HANJA'),
  kanji(0x19, 'KANJI'),
  imeOff(0x1A, 'IME_OFF'),

  escape(0x1B, 'ESCAPE'),
  convert(0x1C, 'CONVERT'),
  nonConvert(0x1D, 'NONCONVERT'),
  accept(0x1E, 'ACCEPT'),
  modeChange(0x1F, 'MODECHANGE'),

  space(0x20, 'SPACE'),
  pageUp(0x21, 'PRIOR'),
  pageDown(0x22, 'NEXT'),
  end(0x23, 'END'),
  home(0x24, 'HOME'),
  left(0x25, 'LEFT'),
  up(0x26, 'UP'),
  right(0x27, 'RIGHT'),
  down(0x28, 'DOWN'),
  select(0x29, 'SELECT'),
  print(0x2A, 'PRINT'),
  execute(0x2B, 'EXECUTE'),
  printScreen(0x2C, 'SNAPSHOT'),
  insert(0x2D, 'INSERT'),
  delete(0x2E, 'DELETE'),
  help(0x2F, 'HELP'),

  digit0(0x30, '0'),
  digit1(0x31, '1'),
  digit2(0x32, '2'),
  digit3(0x33, '3'),
  digit4(0x34, '4'),
  digit5(0x35, '5'),
  digit6(0x36, '6'),
  digit7(0x37, '7'),
  digit8(0x38, '8'),
  digit9(0x39, '9'),

  keyA(0x41, 'A'),
  keyB(0x42, 'B'),
  keyC(0x43, 'C'),
  keyD(0x44, 'D'),
  keyE(0x45, 'E'),
  keyF(0x46, 'F'),
  keyG(0x47, 'G'),
  keyH(0x48, 'H'),
  keyI(0x49, 'I'),
  keyJ(0x4A, 'J'),
  keyK(0x4B, 'K'),
  keyL(0x4C, 'L'),
  keyM(0x4D, 'M'),
  keyN(0x4E, 'N'),
  keyO(0x4F, 'O'),
  keyP(0x50, 'P'),
  keyQ(0x51, 'Q'),
  keyR(0x52, 'R'),
  keyS(0x53, 'S'),
  keyT(0x54, 'T'),
  keyU(0x55, 'U'),
  keyV(0x56, 'V'),
  keyW(0x57, 'W'),
  keyX(0x58, 'X'),
  keyY(0x59, 'Y'),
  keyZ(0x5A, 'Z'),

  leftWindows(0x5B, 'LWIN'),
  rightWindows(0x5C, 'RWIN'),
  apps(0x5D, 'APPS'),
  sleep(0x5F, 'SLEEP'),

  numpad0(0x60, 'NUMPAD0'),
  numpad1(0x61, 'NUMPAD1'),
  numpad2(0x62, 'NUMPAD2'),
  numpad3(0x63, 'NUMPAD3'),
  numpad4(0x64, 'NUMPAD4'),
  numpad5(0x65, 'NUMPAD5'),
  numpad6(0x66, 'NUMPAD6'),
  numpad7(0x67, 'NUMPAD7'),
  numpad8(0x68, 'NUMPAD8'),
  numpad9(0x69, 'NUMPAD9'),
  multiply(0x6A, 'MULTIPLY'),
  add(0x6B, 'ADD'),
  separator(0x6C, 'SEPARATOR'),
  subtract(0x6D, 'SUBTRACT'),
  decimal(0x6E, 'DECIMAL'),
  divide(0x6F, 'DIVIDE'),

  f1(0x70, 'F1'),
  f2(0x71, 'F2'),
  f3(0x72, 'F3'),
  f4(0x73, 'F4'),
  f5(0x74, 'F5'),
  f6(0x75, 'F6'),
  f7(0x76, 'F7'),
  f8(0x77, 'F8'),
  f9(0x78, 'F9'),
  f10(0x79, 'F10'),
  f11(0x7A, 'F11'),
  f12(0x7B, 'F12'),

  numLock(0x90, 'NUMLOCK'),
  scrollLock(0x91, 'SCROLL'),

  leftShift(0xA0, 'LSHIFT'),
  rightShift(0xA1, 'RSHIFT'),
  leftControl(0xA2, 'LCONTROL'),
  rightControl(0xA3, 'RCONTROL'),
  leftAlt(0xA4, 'LMENU'),
  rightAlt(0xA5, 'RMENU'),

  browserBack(0xA6, 'BROWSER_BACK'),
  browserForward(0xA7, 'BROWSER_FORWARD'),
  browserRefresh(0xA8, 'BROWSER_REFRESH'),
  browserStop(0xA9, 'BROWSER_STOP'),
  browserSearch(0xAA, 'BROWSER_SEARCH'),
  browserFavorites(0xAB, 'BROWSER_FAVORITES'),
  browserHome(0xAC, 'BROWSER_HOME'),

  volumeMute(0xAD, 'VOLUME_MUTE'),
  volumeDown(0xAE, 'VOLUME_DOWN'),
  volumeUp(0xAF, 'VOLUME_UP'),
  mediaNextTrack(0xB0, 'MEDIA_NEXT_TRACK'),
  mediaPrevTrack(0xB1, 'MEDIA_PREV_TRACK'),
  mediaStop(0xB2, 'MEDIA_STOP'),
  mediaPlayPause(0xB3, 'MEDIA_PLAY_PAUSE'),
  launchMail(0xB4, 'LAUNCH_MAIL'),
  launchMediaSelect(0xB5, 'LAUNCH_MEDIA_SELECT'),
  launchApp1(0xB6, 'LAUNCH_APP1'),
  launchApp2(0xB7, 'LAUNCH_APP2'),

  oem1(0xBA, 'OEM_1'),
  oemPlus(0xBB, 'OEM_PLUS'),
  oemComma(0xBC, 'OEM_COMMA'),
  oemMinus(0xBD, 'OEM_MINUS'),
  oemPeriod(0xBE, 'OEM_PERIOD'),
  oem2(0xBF, 'OEM_2'),
  oem3(0xC0, 'OEM_3'),

  gamepadA(0xC3, 'GAMEPAD_A'),
  gamepadB(0xC4, 'GAMEPAD_B'),
  gamepadX(0xC5, 'GAMEPAD_X'),
  gamepadY(0xC6, 'GAMEPAD_Y'),
  gamepadRightShoulder(0xC7, 'GAMEPAD_RIGHT_SHOULDER'),
  gamepadLeftShoulder(0xC8, 'GAMEPAD_LEFT_SHOULDER'),
  gamepadLeftTrigger(0xC9, 'GAMEPAD_LEFT_TRIGGER'),
  gamepadRightTrigger(0xCA, 'GAMEPAD_RIGHT_TRIGGER'),
  gamepadDpadUp(0xCB, 'GAMEPAD_DPAD_UP'),
  gamepadDpadDown(0xCC, 'GAMEPAD_DPAD_DOWN'),
  gamepadDpadLeft(0xCD, 'GAMEPAD_DPAD_LEFT'),
  gamepadDpadRight(0xCE, 'GAMEPAD_DPAD_RIGHT'),
  gamepadMenu(0xCF, 'GAMEPAD_MENU'),
  gamepadView(0xD0, 'GAMEPAD_VIEW'),
  gamepadLeftThumbstickButton(0xD1, 'GAMEPAD_LEFT_THUMBSTICK_BUTTON'),
  gamepadRightThumbstickButton(0xD2, 'GAMEPAD_RIGHT_THUMBSTICK_BUTTON'),
  gamepadLeftThumbstickUp(0xD3, 'GAMEPAD_LEFT_THUMBSTICK_UP'),
  gamepadLeftThumbstickDown(0xD4, 'GAMEPAD_LEFT_THUMBSTICK_DOWN'),
  gamepadLeftThumbstickRight(0xD5, 'GAMEPAD_LEFT_THUMBSTICK_RIGHT'),
  gamepadLeftThumbstickLeft(0xD6, 'GAMEPAD_LEFT_THUMBSTICK_LEFT'),
  gamepadRightThumbstickUp(0xD7, 'GAMEPAD_RIGHT_THUMBSTICK_UP'),
  gamepadRightThumbstickDown(0xD8, 'GAMEPAD_RIGHT_THUMBSTICK_DOWN'),
  gamepadRightThumbstickRight(0xD9, 'GAMEPAD_RIGHT_THUMBSTICK_RIGHT'),
  gamepadRightThumbstickLeft(0xDA, 'GAMEPAD_RIGHT_THUMBSTICK_LEFT'),

  oem4(0xDB, 'OEM_4'),
  oem5(0xDC, 'OEM_5'),
  oem6(0xDD, 'OEM_6'),
  oem7(0xDE, 'OEM_7'),
  oem8(0xDF, 'OEM_8'),
  oem102(0xE2, 'OEM_102'),

  processKey(0xE5, 'PROCESSKEY'),
  packet(0xE7, 'PACKET'),

  attn(0xF6, 'ATTN'),
  crSel(0xF7, 'CRSEL'),
  exSel(0xF8, 'EXSEL'),
  eraseEof(0xF9, 'EREOF'),
  play(0xFA, 'PLAY'),
  zoom(0xFB, 'ZOOM'),
  pa1(0xFD, 'PA1'),
  oemClear(0xFE, 'OEM_CLEAR');

  final int vkCode;
  final String label;

  const VirtualKeyCode(this.vkCode, this.label);

  static VirtualKeyCode? tryFromVkCode(int vkCode) {
    for (final value in VirtualKeyCode.values) {
      if (value.vkCode == vkCode) return value;
    }
    return null;
  }
}
